# Generated by Django 6.0.5 on 2026-05-25 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP'), ('UTILITY', 'Utility Portal'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('raw_data', models.JSONField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('FUEL', 'Fuel/Procurement'), ('ELECTRICITY', 'Electricity'), ('TRAVEL', 'Business Travel')], max_length=20)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1'), ('SCOPE_2', 'Scope 2'), ('SCOPE_3', 'Scope 3')], max_length=10)),
                ('activity_date', models.DateField()),
                ('original_value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('original_unit', models.CharField(max_length=50)),
                ('normalized_value_kgco2e', models.DecimalField(decimal_places=4, max_digits=20)),
                ('conversion_factor', models.DecimalField(decimal_places=6, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_rows', to='data_engine.ingestionrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_engine.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('previous_state', models.JSONField(null=True)),
                ('new_state', models.JSONField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='data_engine.normalizedrecord')),
            ],
        ),
        migrations.AddField(
            model_name='ingestionrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_engine.organization'),
        ),
    ]
