# Generated by Django 6.0.5 on 2026-05-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedrecord',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
