# Generated by Django 6.0.5 on 2026-05-25 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0002_normalizedrecord_is_locked_organization_last_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingestionrecord',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='ingestionrecord',
            name='raw_data',
        ),
        migrations.RemoveField(
            model_name='ingestionrecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='normalizedrecord',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_engine.organization'),
        ),
        migrations.AddField(
            model_name='ingestionrecord',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ingestions/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='ingestionrecord',
            name='ingested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingestionrecord',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingestionrecord',
            name='raw_json_summary',
            field=models.JSONField(default=dict, help_text='Extracted data summary for preview.'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='ANALYST', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='data_engine.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
