# Generated by Django 6.0.5 on 2026-05-25 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_engine', '0003_remove_ingestionrecord_error_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrecord',
            name='error_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionrecord',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingestionrecord',
            name='raw_payload',
            field=models.JSONField(blank=True, default=list, help_text='Raw payload from upload or paste'),
        ),
        migrations.AddField(
            model_name='ingestionrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='activity_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='analyst_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='emission_factor',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='kg_co2e',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='normalized_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='raw_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='suspicious_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingestionrecord',
            name='raw_json_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Extracted data summary for preview.'),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged'), ('FAILED', 'Failed'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked')], default='PENDING', max_length=10),
        ),
    ]
